name: WheresMyBones
main: com.mouthpunch.wheresmybones.WheresMyBones
version: 1.2.5.0
commands:
    mybones:
        description: Gives the locations of your last few deaths
        usage: /mybones [<bone number> [compass]]